# H2
spring:
  datasource:
    url: jdbc:h2:mem:lifeshare
    driverClassName: org.h2.Driver
    username: fivelife
    password: 1515-lifeshare
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2